In [1]:
import numpy as np

In [2]:
R = np.matrix([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],   # this door can go to door 5 as winning
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,0,-1],
    [0,-1,-1,0,-1,100],
    [-1,0,-1,-1,0,100]
    
])
    
    
    
    

In [3]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [  0,  -1,  -1,   0,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [4]:
Q =np.zeros([6,6])

In [5]:
Q

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
initial_state = 1
gamma = 0.8 # between 0 and 1

In [7]:
def available_act(state):
    current_state_row =  R[state,]
    av_action = np.where(current_state_row > -1)[1]
    return av_action

In [8]:
available_act(initial_state)

array([3, 5])

In [9]:
#exploiration -- making a random choice
def sample_next_action(available_actions):
    next_action = int(np.random.choice(available_actions,1))  # select only 1 random option
    return next_action

In [10]:
action= sample_next_action(available_act(initial_state))

In [11]:
# dummy create a function to update
def update(current_state, action, gamma):
    max_index = np.where(Q[action,] == np.max(Q[action,]))[0]  # chooce the one giving me the max reward
    
    if max_index.shape[0]>1:
        max_index = int(np.random.choice(max_index,1))  ## some records have multiple zeros as the max
    else:
        max_index =int(max_index)
        
    max_value=Q[action,max_index]
    Q[current_state,action]= int(R[current_state,action]+gamma*max_value)  # this is standard formula

In [12]:
update(initial_state,action,gamma)

In [13]:
Q

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.]])

In [14]:
for i in range(10000):
    current_state = np.random.randint(0,int(Q.shape[0]))
    available_actions = available_act(current_state)
    action = sample_next_action(available_actions)
    update(current_state,action, gamma)

In [15]:
Q

array([[  0.,   0.,   0.,   0., 396.,   0.],
       [  0.,   0.,   0., 316.,   0., 496.],
       [  0.,   0.,   0., 316.,   0.,   0.],
       [  0., 396., 252.,   0., 396.,   0.],
       [316.,   0.,   0., 316.,   0., 496.],
       [  0., 396.,   0.,   0., 396., 496.]])

In [22]:
print('Normalised Trained Q matrix')
Q/np.max(Q)*100  # normalized matrix. 

Normalised Trained Q matrix


array([[  0.        ,   0.        ,   0.        ,   0.        ,
         79.83870968,   0.        ],
       [  0.        ,   0.        ,   0.        ,  63.70967742,
          0.        , 100.        ],
       [  0.        ,   0.        ,   0.        ,  63.70967742,
          0.        ,   0.        ],
       [  0.        ,  79.83870968,  50.80645161,   0.        ,
         79.83870968,   0.        ],
       [ 63.70967742,   0.        ,   0.        ,  63.70967742,
          0.        , 100.        ],
       [  0.        ,  79.83870968,   0.        ,   0.        ,
         79.83870968, 100.        ]])

In [21]:
current_state = 2
step = [current_state]

while current_state !=5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]
    #print(next_step_index)
    
    if next_step_index.shape[0] >1:
        next_step_index = int(np.random.choice(next_step_index,1))
    else:
        next_step_index= int(next_step_index)
    step.append(next_step_index)
    current_state=next_step_index
step

[2, 3, 4, 5]

In [20]:
current_state

5